# Generated by Django 4.0.4 on 2022-06-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_choice', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Registered templates',
            },
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'All available posts!'},
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.templatechoice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User template picks',
            },
        ),
    ]
