# Generated by Django 4.0.4 on 2022-07-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_templatechoice_alter_posts_options_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='template',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.templatechoice'),
        ),
    ]
